function h = add_status_badge(ax, label, position, bgColor, fgColor)
%ADD_STATUS_BADGE Add a compact status label on top of a plot or image.

if nargin < 3 || isempty(position)
    position = [0.02 0.94];
end
if nargin < 4 || isempty(bgColor)
    bgColor = [0.14 0.18 0.26];
end
if nargin < 5 || isempty(fgColor)
    fgColor = [1 1 1];
end

h = text(ax, position(1), position(2), label, ...
    'Units', 'normalized', ...
    'Interpreter', 'none', ...
    'FontWeight', 'bold', ...
    'FontSize', 8.5, ...
    'Color', fgColor, ...
    'BackgroundColor', bgColor, ...
    'Margin', 2, ...
    'VerticalAlignment', 'top', ...
    'HorizontalAlignment', 'left');
end
