function apply_axes_theme(target, mode)
%APPLY_AXES_THEME Apply a consistent presentation style to axes or figures.

if nargin < 2 || isempty(mode)
    mode = "plot";
end
mode = lower(string(mode));

if isa(target, 'matlab.ui.Figure') || (isgraphics(target) && strcmp(get(target, 'Type'), 'figure'))
    set(target, 'Color', 'w', 'InvertHardcopy', 'off');
    axesList = findall(target, 'Type', 'axes');
    for i = 1:numel(axesList)
        apply_axes_theme(axesList(i), mode);
    end
    return;
end

if ~isgraphics(target) || ~strcmp(get(target, 'Type'), 'axes')
    return;
end

ax = target;
set(ax, ...
    'FontName', 'Helvetica', ...
    'FontSize', 10, ...
    'LineWidth', 1.0, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'Layer', 'top');

if isprop(ax, 'ColorOrder')
    ax.ColorOrder = [ ...
        0.12 0.47 0.71; ...
        0.00 0.62 0.45; ...
        0.84 0.37 0.00; ...
        0.59 0.29 0.64; ...
        0.89 0.10 0.11; ...
        0.49 0.18 0.56; ...
        0.23 0.61 0.83];
end

switch mode
    case "image"
        set(ax, ...
            'Color', 'w', ...
            'XColor', [0.28 0.28 0.28], ...
            'YColor', [0.28 0.28 0.28], ...
            'XGrid', 'off', ...
            'YGrid', 'off');
    otherwise
        set(ax, ...
            'Color', [0.995 0.996 0.998], ...
            'XColor', [0.18 0.18 0.18], ...
            'YColor', [0.18 0.18 0.18], ...
            'ZColor', [0.18 0.18 0.18], ...
            'GridAlpha', 0.14, ...
            'MinorGridAlpha', 0.06, ...
            'XGrid', 'on', ...
            'YGrid', 'on', ...
            'ZGrid', 'on');
        if isprop(ax, 'XMinorGrid')
            ax.XMinorGrid = 'on';
            ax.YMinorGrid = 'on';
        end
        if isprop(ax, 'ZMinorGrid')
            ax.ZMinorGrid = 'on';
        end
end
end
